### ISSUE TITLE
Créer une commande qui télécharge le plan de compte 2018

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#1]
Créer une commande `npm run download-plansdecompte <année>`.

Ce que j'ai fait, manuellement, pour le plan 2017 : 

```bash
curl http://odm-budgetaire.org/composants/normes/2017/M14/M14_COM_SUP3500/planDeCompte.xml \
  | iconv -f iso-8859-1 \
  > data/finances/plansDeCompte/M14-M14_COM_SUP3500-2017.xml
```

**Comment by DavidBruant** [comment]
Réflexions sur le même sujet 
https://github.com/datalocale/dataviz-finances-gironde/issues/451#issuecomment-449022605

**Comment by DavidBruant** [comment]
J'ai commencé à travailler sur un tel outil dans un repo séparé : https://github.com/dtc-innovation/plans-de-compte
