### ISSUE TITLE
Pour les DI, faire que les bulles soient le découpage politique de Dépenses d'équipement

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/dataviz-finances-montreuil#103]
Comme pour DF/"Gestion courante"

**Comment by oncletom** [comment]
Suite à l'appel du jour, ça peut être généralisé à tout : DI, DF, RI et RF.

**Comment by DavidBruant** [comment]
Si je comprends bien, on peut fermer cette issue en faveur de #110

**Comment by oncletom** [comment]
Yes !
