### ISSUE TITLE
L’ensemble des catégories des dépenses réelles de fonctionnement n’apparait pas.

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#108]
On voit seulement la « gestion courante » et l’ « intercommunalité »

On devrait avoir également : « charge de la dette », « péréquation »

![image](https://user-images.githubusercontent.com/138627/58694059-70a77f80-8392-11e9-8248-26105d6d913f.png)

**Comment by DavidBruant** [comment]
J'observe que côté data, je ne vois que ces deux enfants dans les enfants de DF

**Comment by oncletom** [comment]
Dans le CSV il y a des lignes Interco dans les DF :

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/138627/58870932-67375380-86c1-11e9-9615-2e054d817d29.png">

Idem pour Péréquation : 

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/138627/58870984-7ae2ba00-86c1-11e9-930c-0361dac550f9.png">

**Comment by DavidBruant** [comment]
Sur l'actuel master https://github.com/dtc-innovation/dataviz-finances-montreuil/commit/cfb1581570498dcf274e5133e4e955d8aa31da63 , lors de la production des données (`MontreuilNomenclatureToAggregationDescription`), DF n'a que ces 2 enfants

Les lignes de `montreuilNomenclature` sont filtrées. Ce filtre enlève tous les opérations d'ordre et toutes les lignes qui ne sont dans aucun document budgétaire. Donc j'imagine que les document budgétaires ne référencent pas les lignes du CSV

De mémoire, il y avait des lignes non-utilisées. Est-ce que ce problème a été corrigé, @oncletom ?

**Comment by oncletom** [comment]
Du côté de Montreuil, il y a un constat que les 5 premières lignes non-utilisées sont dans le fichier `Natures - Fonctions v7` et dans le XML 2018 mais n'apparaissent pas dans la viz. Ils ne sont pas allés plus loin, pensant qu'il y avait un bug de notre côté : 

Exemple avec 

```
DF | F020 | C011 | N611
```

Je le retrouve dans le tableau v7 : 

```csv
DEPENSE,REELLE,FONCTIONNEMENT,11,CHARGES A CARACTERE GENERAL,611,CONTRATS PREST SERV ENTREPRISE,20,ADMIN GENERALE COLLECTIVITE,DEPENSE REELLE FONCTIONNEMENT,Gestion courante,Prestations extérieures,Administration générale,Administration générale
```

Et dans le XML : 

```xml
      <LigneBudget>
         <Nature V="611"/>
         <Fonction V="020"/>
         <ContNat V="011"/>
         <ArtSpe V="false"/>
         <CodRD V="D"/>
         <MtPrev V="0.00"/>
         <CredOuv V="853017.08"/>
         <MtReal V="766078.42"/>
         <OpBudg V="0"/>
         <MtSup Code="BudgetHorsRAR" V="853017.08"/>
         <MtSup Code="ProdChaRat" V="743427.79"/>
      </LigneBudget>
```

Idem sur les charges de la dette : 

```
DF | F01 | C66 | N66111 | 4082140.61
```

```csv
DEPENSE,REELLE,FONCTIONNEMENT,66,CHARGES FINANCIERES,66111,INTERETS REGLES A L'ECHEANCE,1,OPERATIONS NON VENTILABLES,DEPENSE REELLE FONCTIONNEMENT,Charge de la dette,-,Charge de la dette,-
```

```xml
      <LigneBudget>
         <Nature V="66111"/>
         <Fonction V="01"/>
         <ContNat V="66"/>
         <ArtSpe V="false"/>
         <CodRD V="D"/>
         <MtPrev V="0.00"/>
         <CredOuv V="4939424.40"/>
         <MtReal V="4082140.61"/>
         <OpBudg V="0"/>
         <MtSup Code="BudgetHorsRAR" V="4939424.40"/>
      </LigneBudget>
```

Est-ce que je n'ai pas les yeux en face des trous ou est-ce que je rate quelque chose dans le cheminement des données entre la source XML et les différentes étapes de filtre ?

**Comment by DavidBruant** [comment]
ok, jvais regarder plus tard dans l'aprèm

**Comment by DavidBruant** [comment]
> > DF | F020 | C011 | N611
>
> Je le retrouve dans le tableau v7 :
>
> > DEPENSE,REELLE,FONCTIONNEMENT,11,CHARGES A CARACTERE GENERAL,611,CONTRATS PREST SERV ENTREPRISE,20,ADMIN GENERALE COLLECTIVITE,DEPENSE REELLE FONCTIONNEMENT,Gestion courante,Prestations extérieures,Administration générale,Administration générale

ok, c'est bon, je crois que j'ai trouvé `F020`, c'est la fonction `020` (le `0` initial est significatif et signifie notamment que `020` est une sous-fonction de la fonction `0`, "Services généraux des administrations publiques locales"). Dans la ligne dans le CSV, cette fonction est noté `20` qui est une autre fonction que la fonction `020`

Même problème avec `DF | F01 | C66 | N66111 | 4082140.61`, fonctions `01` et `1`

Je vais voir le Excel, voir s'il y a une chance de récupérer les bonnes données avec les préfixes `0`

**Comment by oncletom** [comment]
Ah ! C'est tellement ma faute… j'ai réalisé la conversion en ligne de commande avec [`csvkit`](https://csvkit.readthedocs.io/en/latest/scripts/in2csv.html) et je réalise via ta correction qu'il fait de l'inférence de type, et donc qu'il a viré les préfixes `0` 😭 

Merci beaucoup 👍

**Comment by oncletom** [comment]
Je reprends la liste des lignes non-utilisées, par exemple, la première ligne : 

```
DF | F020 | C011 | N611 | 766078.42
```

Dans le CA 2018, c'est cette ligne : 

```xml
      <LigneBudget>
         <Nature V="611"/>
         <Fonction V="020"/>
         <ContNat V="011"/>
         <ArtSpe V="false"/>
         <CodRD V="D"/>
         <MtPrev V="0.00"/>
         <CredOuv V="853017.08"/>
         <MtReal V="766078.42"/>
         <OpBudg V="0"/>
         <MtSup Code="BudgetHorsRAR" V="853017.08"/>
         <MtSup Code="ProdChaRat" V="743427.79"/>
      </LigneBudget>
```

Dans le plan de compte : 

```xml
<Compte Code="611" Libelle="Contrats de prestations de services" Lib_court="Contrats de prestations de services" DEquip="0" DR="011" DOES="" DOIS="" REquip="0" RR="" ROES="" ROIS=""/>
```

Et dans le Excel/CSV : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/59016123-e606ca80-8840-11e9-8d36-0619f2416ef3.png">

C'est censé apparaître dans la politique "Administration générale" puis la sous-politique "Administration générale".

Pourtant, dans le tableau je ne vois pas cette ligne à `7,67M€` : 

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/138627/59016242-1a7a8680-8841-11e9-9b59-beba587b49a2.png">

T'en penses quoi ?

**Comment by DavidBruant** [comment]
> DF | F020 | C011 | N611 | 766078.42

> Pourtant, dans le tableau je ne vois pas cette ligne à 7,67M€ sur la page associée à Administration Générale/Administration Générale

J'ai l'impression que la somme est `766078.42€` (Environ `766 000€`) et pas "7,67M€" (`7 670 000€`). Je vois une ligne correspondant dans la page vers laquelle tu lies. Ça serait la 14ème ligne (notée `Administration générale de la collectivité | Contrats de prestations de services | 0,8 M€`)

Est-ce que tu vois ça aussi ?

**Comment by oncletom** [comment]
Baaaah 🙃

Je la vois. Désolé pour la perte de temps :-(

Merci !
