### ISSUE TITLE
StackChart : la palette de couleurs s'arrête à 10

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#133]
![image](https://user-images.githubusercontent.com/138627/59776771-a82f8a80-92b3-11e9-80ee-0452a5062636.png)

Avec Gestion courante, on monte à 18 couleurs !

@sofiaboulaarab t'as une idée ?

**Comment by sofiaboulaarab** [comment]
Yes ! Je m’en occupe dans la semaine. Est ce que l’on va également
atteindre un chiffre du même ordre pour les recettes ?

Le mer. 19 juin 2019 à 17:03, Thomas Parisot <notifications@github.com> a
écrit :

**Comment by oncletom** [comment]
On n'atteint pas 18 niveaux dans les autres sections (que ça soit en dépense ou recette). Tu peux t'en apercevoir dans le lien de preview de #119.

![image](https://user-images.githubusercontent.com/138627/59859432-f78dbd80-937c-11e9-9d9a-78af605a5dbc.png)

**Comment by sofiaboulaarab** [comment]
"D'ailleurs, je peux aussi générer les couleurs en me basant sur la palette initiale (genre shifter des couleurs vers du sombre/clair, vers un autre endroit du disque de couleurs, etc.)" @oncletom très bonne idée à vois si ça fonctionne mieux / moins bien que l'ajout de nouveaux codes couleurs que voici : #D574BA #DAA9CC #9D0D6C #F5A683 #D9A08D #B67979 #D53131

Avec un petit aperçu
<img width="1209" alt="Screenshot 2019-06-24 at 07 39 53" src="https://user-images.githubusercontent.com/47563147/59994454-2c876200-9654-11e9-83ed-11de443a298d.png">

On commence à atteindre un chiffre conséquent, je ne suis pas sur que les utilisateurs vont aller chercher dans la légende à quelle couleur correspond quelle portion du graphique, je me dis qu'ils vont sans doute plutôt compter sur le survol des blocs : à verifier pendant les tests :)

**Comment by oncletom** [comment]
Oui, carrément ! En survolant les libellés et les briques 👍

**Comment by oncletom** [comment]
![image](https://user-images.githubusercontent.com/138627/60004595-336e9e80-966d-11e9-98fa-2dc36f65020c.png)

**Comment by sofiaboulaarab** [comment]
C’est top !

Le lun. 24 juin 2019 à 10:45, Thomas Parisot <notifications@github.com> a
écrit :
