### ISSUE TITLE
Grands Chiffres : Afficher l'excédent/déficit entre les Revenus et les Dépenses

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#141]

**Comment by sofiaboulaarab** [comment]
@oncletom j'ai un peu du mal à me projeter sur celui-ci. Est-ce qu'on modifie la visualisation pour afficher un graphe de type balance ?

**Comment by oncletom** [comment]
Je ne sais pas trop ; c'est pas un point bloquant, on peut ne pas trouver de solution pour le moment.
