### ISSUE TITLE
Baliser les endroits où afficher des % pour éclairer les comparaisons

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#142]

**Comment by oncletom** [comment]
Voilà basiquement ce que j'avais en tête.

![Screenshot_2019-07-03 Dataviz finances (démo)](https://user-images.githubusercontent.com/138627/60578859-41fe3980-9d82-11e9-938e-8e783da83f75.png)

**Comment by oncletom** [comment]
@sofiaboulaarab j'ai ajouté des endroits où j'ai l'impression que les participant·es des entretiens auraient gagnés en repères de comparaison. Ça te parle ?

**Comment by sofiaboulaarab** [comment]
@oncletom au top ! merci je mets à jour les maquettes, et je te dis quand c'est ok !

**Comment by sofiaboulaarab** [comment]
@oncletom propositions pour l'affichage des pourcentages
<img width="514" alt="Screenshot 2019-07-11 at 18 22 17" src="https://user-images.githubusercontent.com/47563147/61067982-27befe00-a409-11e9-8934-a9c4d04a019e.png">
<img width="558" alt="Screenshot 2019-07-11 at 18 23 30" src="https://user-images.githubusercontent.com/47563147/61067985-2a215800-a409-11e9-812a-54b553b94d04.png">
<img width="389" alt="Screenshot 2019-07-11 at 18 23 19" src="https://user-images.githubusercontent.com/47563147/61067989-2b528500-a409-11e9-9b41-1603e04d9188.png">
<img width="671" alt="Screenshot 2019-07-11 at 18 24 10" src="https://user-images.githubusercontent.com/47563147/61067992-2c83b200-a409-11e9-89a5-740cb7058eda.png">
Link : https://www.figma.com/file/NKgSOd1pwalNQPx2LTTy5sTx/Dataviz-Montreuil?node-id=460%3A987

**Comment by sofiaboulaarab** [comment]
Un peu de boulot au niveau éditorial, mais d'expérience c'est plus évident cognitivement qu'on mise : ce que tu regardes représente "tant de % de quelque chose, et c'est égale à ce chiffre"

**Comment by sofiaboulaarab** [comment]
dernier point : a quoi correspond le +2M sur les grands chiffres ?

**Comment by oncletom** [comment]
Super 👍 

Le `+2M` faisait référence au calcul de l'excédent/déficit mais ma demande est hors-sujet.
