### ISSUE TITLE
Remplacer les mentions visibles de M52 par M14

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#23]
- [ ] dans les URLs
- [ ] dans les textes lisibles

**Comment by DavidBruant** [comment]
J'ai l'impression que le problème à résoudre, c'est surtout faire disparaitre les mentions de M52

Parfois, la solution, c'est d'utiliser un terme plus générique ; pas forcément mettre "M14"

**Comment by oncletom** [comment]
Tu penses à un terme générique en particulier ? Ou certains, en fonction d'usages particuliers ?

**Comment by DavidBruant** [comment]
Par exemple, `hierarchicalM52.js` pourrait être renommé `hierarchicalByFunction.js`

`M52Entry` pourrait être remplacé par `LigneBudget` (ou autre chose qui fait une référence à l'élément XML du même nom, mais un peu différent parce qu'on modifie un peu les "metadata" de la ligne)

Beaucoup d'instances sont issues du fait que je découvrais le métier des finances publiques et que "M52" semblait être le qualificateur le plus pertinent

**Comment by oncletom** [comment]
Dac, je vois — ça serait l'objet d'une autre issue (j'y ai pensé mais c'était pas impact côté utilisateur).

Celle-ci concerne les mentions du terme M52 visibles par le grand public en parcourant la dataviz.

**Comment by DavidBruant** [comment]
ah oki, j'avais mal compris\
pardon pour le bruit

**Comment by ariasuni** [comment]
Je ne vois pas de mention M52 dans les pages que je peux visiter ni dans les CSV des labels. Je vois juste `/build/m52-overview-bundle.js` dans les URL à priori.
