### ISSUE TITLE
Remplacer les chemins de fichier hardcodés

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#24]
`M14-M14_COM_SUP3500-2017.xml` et `CA 2017.xml` sont hardcodés dans plusieurs fichiers.

L'attente est de "lire les fichiers *.xml de tel ou tel répertoire" et de passer ce résultat aux fonctions qui les consomment.

**Comment by oncletom** [comment]
Pour précision, je pense au code dans : 
- `tools/make-doc-budg-strings.js`
- `tools/make-public-data.js`

`m52-overview/js/main.js` peut rester hardcodé — ou la valeur du fichier peut être passé par une variable d'environnement (voir du côté de la config `babel-plugin-transform-inline-environment-variables`).

**Comment by ariasuni** [comment]
Comment j’appelle les variables qui contiendront les noms de `M14-M14_COM_SUP3500-2017.xml` et `CA 2017.xml`? Pour le 2e je vois bien `xml_CA` ou un truc du genre, mais pour le premier je suis moins sure.

**Comment by ariasuni** [comment]
J’ai essayé de remplacer ça par des variables d’environnement, mais du coup je dois les recopier plusieurs fois dans le `package.json` et je vois pas comment faire ça de façon propre du coup

**Comment by oncletom** [comment]
Commence avec ce que tu vois et on avisera si l'effort à faire pour optimiser ça vaut le coup à ce stade du projet, dac ?
