### ISSUE TITLE
Importer l’icono SVG inline

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#3]
Pour 3 raisons : 

- portabilité (les images n'ont pas besoin d'être importées sur l'environnement de déploiement)
- pour ne plus se baser sur rawgit (cf `resources.js`)
- pour ne pas appeler de fichier externe supplémentaires autres que le bundle JS et le bundle CSS.

Y'a surement un transform browserify, react ou babel pour ça (exemple : [babel-plugin-inline-react-svg](https://npmjs.com/babel-plugin-inline-react-svg), [babel-plugin-inline-svg](https://npmjs.com/babel-plugin-inline-svg)).

**Comment by ariasuni** [comment]
Du coup l’idée c’est de garder le `resources.js` tel quel mais de l’inliner lors de la construction du composant React, c’est ça?

**Comment by oncletom** [comment]
Je pensais à virer les références aux SVG dans `resources.js` et à faire les imports directement dans les pages focus qui les utilisent. 

Par exemple : 

```
import ElectricitePicto from '../bla/bla/depensesElectricite.svg`

// ...

  render () {
    // ...
      React.createElement(ElectricitePicto, className="blah")
    // ...
  }
```

**Comment by ariasuni** [comment]
Je vais faire une PR et tu me diras si c’est bon comme j’ai fait ou si tu préfères comme ce que tu indiques dans ton commentaire.
