### ISSUE TITLE
Page Explorer : calculer les grandes masses budgétaires qui correspondent au CA 2017

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#4]
Composant `ExploreBudget`, près de la variable `constructionAmounts`.

**Comment by oncletom** [comment]
Les dépenses de fonctionnement devrait être un total de 203K (DRF 192M + DOF 10M).
Confirmable en lisant le CA_2017_1.pdf (dans les 10 premières pages)

Pour les masses budgétaires, il devrait y avoir les entêtes de colonne de la page 35.

Y'a des subventions d'investissement et d'autres de fonctionnement. Celles de fonctionnement sont labellisées "Participations". Page 16, le total devrait être la somme de 2 colonnes (X et Y).

---

Navigation par chapitre puis nature ?

**Comment by oncletom** [comment]
Les totaux devraient être les suivants 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/138627/52777386-fd2c6d00-3043-11e9-8394-b61eee91063a.png">

**Comment by oncletom** [comment]
On retrouve les dépenses de fonctionnement comme étant la somme des fonctions (?).

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/138627/52785462-57cfc400-3058-11e9-9340-e1f072a2c95f.png">

**Comment by DavidBruant** [comment]
Pour reprendre ce que tu as écris sur Slack : 

> les masses budgétaires sont construites à partir de la version agrégée [pour la Gironde]

Oui\
Vu qu'on ne fait sûrement pas d'agrégation pour Montreuil, ce calcul doit être refait à partir des donnes brutes. Exemple : 
https://github.com/datalocale/dataviz-finances-gironde/blob/gh-pages/build/finances/doc-budgs.json#L9-L24

Le champ `CodRD` contient `R`(ecettes) ou `D`(épenses)\
Le champ `FI` contient `F`(onctionnement) ou `I`(nvestissement)

Le choix de l'agrégation de calculer les masses à partir de l'agrégation avait été fait en Gironde pour maximiser les chances d'incohérences entre les totaux connus et les totaux depuis l'agrégation (et donc que ça soit visible et qu'on se penche à les corriger)

**Comment by DavidBruant** [comment]
Je pense que tu devrais arriver au résultat correct assez facilement à coup de `.filter` et `d3.sum`

Je rajoute un petit point d'attention sur le fait que le traitement XML => JSON contient du code qui supprime certaines lignes comptables : 
https://github.com/datalocale/dataviz-finances-gironde/blob/baaaab3aae6d448ad5609a4fa698f1bb90dcdf10/src/shared/js/finance/xmlDocumentToDocumentBudgetaire.js#L15-L24 

De mémoire, ces lignes comptables sont des "hacks" pour représenter notamment la trésorerie et un autre truc qui n'ont pas d'existence réelle dans l'exercice comptable\
Les références aux natures et fonctions sont corrects pour la M52. Je soupçonne que la même convention est utilisé dans les autres nomenclature, mais sans preuve

**Comment by oncletom** [comment]
OK, on a les bons montants pour les patates du haut !

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/138627/52964377-70b2df00-33a2-11e9-9b12-d4ef08946a7b.png">
