### ISSUE TITLE
Review template exploration et détail suite réunion Wilfred

### ISSUE THREAD

**Issue by sofiaboulaarab** [dtc-innovation/dataviz-finances-montreuil#43]

**Comment by sofiablb** [comment]
Voilà les différentes pistes - lien : https://www.figma.com/file/NKgSOd1pwalNQPx2LTTy5sTx/Dataviz-Montreuil?node-id=149%3A622
![exploration_proposition1_alt1](https://user-images.githubusercontent.com/47563147/53647712-69ab8c80-3c3e-11e9-8534-028113093dd7.jpg)
![exploration_proposition1_alt2](https://user-images.githubusercontent.com/47563147/53647717-6b755000-3c3e-11e9-92ef-28aef004e00e.jpg)
![exploration_proposition2_all](https://user-images.githubusercontent.com/47563147/53647718-6ca67d00-3c3e-11e9-9fa4-2045d613612f.jpg)
![Uploading Exploration_Proposition2_Depenses.jpg…]()

**Comment by sofiablb** [comment]
Piste 2
![exploration_proposition2_all](https://user-images.githubusercontent.com/47563147/53647862-b4c59f80-3c3e-11e9-9c56-d80f225ff13b.jpg)
![exploration_proposition2_depenses](https://user-images.githubusercontent.com/47563147/53647865-b5f6cc80-3c3e-11e9-8467-8f2a319f989b.jpg)
