### ISSUE TITLE
Générer les formules d'agrégation à partir du fichier Excel des formules

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#47]
Se base sur #46.

Le fichier Excel/CSV est transformé/interprété de sorte à ce `m52ToAggregated.js` recrache un arbre hiérarchique.

Le fichier Excel/CSV sera par la suite mis à jour pour atteindre une partition complète.

**Comment by oncletom** [comment]
Je ne sais pas non plus pour le niveau a/b (politique, sous-politique), c'est quelque chose qui est nouveau qui n'avait pas été discuté avant de recevoir le fichier.

**Comment by oncletom** [comment]
(complément d'information demandé à Julien (en combinaison de #65).

**Comment by DavidBruant** [comment]
Quelques réponses de Montreuil par email : 

> > on enlève les opérations d'ordre (qui sont quand même dans le CSV nomenclaure ?)
> 
> Effectivement on peut éliminer les opérations d'ordre.

Concernant les niveaux a et b : 

> les a & b s'entendent comme des niveaux 4 et 5 après le classement par "nature" 

Il est possible qu'un autre ordre soit préféré plus tard. Commençons avec cette hypothèse en codant quelque chose de flexible
