### ISSUE TITLE
Page détails : revoir la partie qui combine "fil d'ariane" et "part dans les niveaux parents"

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#56]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/138627/53400034-50d87800-39ad-11e9-8f87-d320e56b30d4.png">

**Comment by oncletom** [comment]
@sofiablb, je te laisse reformuler si besoin.

**Comment by sofiablb** [comment]
J'ai réfléchis à un système de navigation avec un système de filtres, à voir si c'est jouable :)
https://www.figma.com/file/NKgSOd1pwalNQPx2LTTy5sTx/Dataviz-Montreuil?node-id=149%3A622

<img width="866" alt="screenshot 2019-03-01 at 17 41 50" src="https://user-images.githubusercontent.com/47563147/53652699-ca8c9200-3c49-11e9-8698-1df6dd81096e.png">
