### ISSUE TITLE
Vérifier que https://dtc-innovation.github.io/anonymisation-document-budgetaire/ fait le travail attendu sur le fichier `CA 2017.xml`

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#6]

**Comment by oncletom** [comment]
Les dépenses de fonctionnement devrait être un total de 203K (DRF 192M + DOF 10M).
Confirmable en lisant le CA_2017_1.pdf

**Comment by oncletom** [comment]
Première réaction : a priori non.

À confirmer.

**Comment by DavidBruant** [comment]
Je veux bien fouiller ce sujet\
Qu'est-ce qui mène à la conclusion que l'anonymisation n'est pas faite correctement ?

**Comment by oncletom** [comment]
Ah pardon, je répondais à une autre question que celle en titre d'issue : "a priori non, on ne voit pas ce qu'il y aurait d'autre à anonymiser".

@DavidBruant d'ailleurs, les prénoms/noms des personnes individuelles qui reçoivent une aide sont lisibles sur le CA 2017. Qu'est-ce qui fait que ces noms seraient retirés du XML utilisés pour la dataviz ?

**Comment by DavidBruant** [comment]
> Qu'est-ce qui fait que ces noms seraient retirés du XML utilisés pour la dataviz ?

J'ai la mémoire un peu floue sur ce point

Je crois que y'a aussi une histoire de "une donnée est pour un usage" et donc c'est ok que ça soit consultable dans le contexte de la version papier, mais c'est trop facile de l'extraire et recroiser avec d'autres données (donc autre usage) en version numérique

(ptèt aussi que c'est pas légal dans la version papier non plus ?)

Donc on a plutôt visé la prudence

**Comment by oncletom** [comment]
Ah merci, je comprends mieux cette décision :) ça me va de la suivre et d'ouvrir la discussion avec le service des finances ou les personnes de la team opendata.
