### ISSUE TITLE
Demander à la Com de nous envoyer la font "Costa"

### ISSUE THREAD

**Issue by sofiablb** [dtc-innovation/dataviz-finances-montreuil#60]

**Comment by oncletom** [comment]
Les personnes qui m'ont envoyé la charte sont Nicolas Nalbe et Ghyslaine Minet.

**Comment by oncletom** [comment]
@sofiablb tu penses qu'on en a besoin ? Je ne l'ai pas vu utilisée sur leur site web.

**Comment by oncletom** [comment]
Pardon, je raconte des cracks !

La police est déjà embarquée sur leur site web. On peut en bénéficier par mimétisme.
Je la mentionne dans #44.
