### ISSUE TITLE
La "nomenclature open data" fournie ne constitue pas une partition

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/dataviz-finances-montreuil#65]
De mes premiers tests en local, je trouve des (136) lignes budgétaires qui font partie du Compte Administratif 2017, mais qui sont omis par la [nomenclature fournie en xlsx](https://github.com/dtc-innovation/dataviz-finances-montreuil/issues/46#issuecomment-468687061)

Une vérification manuelle me permet de voir qu'entre les lignes 12364 et 12375 du fichier du CA 2017, on trouve la ligne : 
```xml
      <LigneBudget>
         <Nature V="657361"/>
         <Fonction V="251"/>
         <ContNat V="65"/>
         <ArtSpe V="false"/>
         <CodRD V="D"/>
         <MtPrev V="0.00"/>
         <CredOuv V="1042231.00"/>
         <MtReal V="1035995.00"/>
         <OpBudg V="0"/>
         <MtSup Code="BudgetHorsRAR" V="1042231.00"/>
      </LigneBudget>
```

Cette ligne est associée à la fonction 251 et la nature 657361. Il n'y a pas de ligne dans le fichier xlsx qui nous permette d'associer cette combinaison aux différents niveaux.

<details>
  <summary>En vrac les lignes concernées que j'ai trouvé</summary>
<table><tr><td>DF</td><td>F022</td><td>C012</td><td>N6336</td><td>12656.13</td></tr><tr><td>DF</td><td>F110</td><td>C012</td><td>N6488</td><td>1483.87</td></tr><tr><td>DF</td><td>F048</td><td>C012</td><td>N6488</td><td>1701.75</td></tr><tr><td>DI</td><td>F812</td><td>C21</td><td>N21571</td><td>309615.04</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6458</td><td>9159.4</td></tr><tr><td>DF</td><td>F026</td><td>C012</td><td>N6488</td><td>1145.18</td></tr><tr><td>DF</td><td>F820</td><td>C012</td><td>N6488</td><td>167.3</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6474</td><td>310.91</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6458</td><td>14311.23</td></tr><tr><td>RF</td><td>F512</td><td>C74</td><td>N7461</td><td>488557</td></tr><tr><td>DF</td><td>F312</td><td>C012</td><td>N6488</td><td>4521.05</td></tr><tr><td>DF</td><td>F512</td><td>C012</td><td>N6488</td><td>815.72</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6331</td><td>10937.79</td></tr><tr><td>DF</td><td>F824</td><td>C012</td><td>N6488</td><td>10923.72</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N64731</td><td>13497.7</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N64111</td><td>461795.52</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6453</td><td>196903.71</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6474</td><td>3745.91</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6455</td><td>5692.52</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6453</td><td>146787.28</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6478</td><td>900</td></tr><tr><td>DF</td><td>F024</td><td>C012</td><td>N6488</td><td>2241.44</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6182</td><td>447.71</td></tr><tr><td>DF</td><td>F422</td><td>C012</td><td>N6488</td><td>9786.37</td></tr><tr><td>DF</td><td>F30</td><td>C012</td><td>N6488</td><td>1081.69</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6336</td><td>7794.79</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6455</td><td>2967.12</td></tr><tr><td>DF</td><td>F822</td><td>C012</td><td>N6488</td><td>2551.95</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6488</td><td>2604.69</td></tr><tr><td>DF</td><td>F251</td><td>C65</td><td>N657361</td><td>1035995</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N64118</td><td>138008.06</td></tr><tr><td>DI</td><td>F422</td><td>C13</td><td>N1328</td><td>919.39</td></tr><tr><td>DF</td><td>F023</td><td>C012</td><td>N6488</td><td>5501.42</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6331</td><td>36132.75</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6455</td><td>2977.67</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6068</td><td>2387.87</td></tr><tr><td>RF</td><td>F022</td><td>C74</td><td>N74718</td><td>8690.4</td></tr><tr><td>RF</td><td>F523</td><td>C70</td><td>N7066</td><td>305</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6455</td><td>4897.82</td></tr><tr><td>DF</td><td>F524</td><td>C012</td><td>N6488</td><td>184.94</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N64118</td><td>140487.02</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6488</td><td>1957.78</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6451</td><td>163316.16</td></tr><tr><td>DF</td><td>F61</td><td>C012</td><td>N6488</td><td>3676.18</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6474</td><td>3652.06</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N64131</td><td>94745.08</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N64118</td><td>311757.35</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6236</td><td>7705.74</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6453</td><td>218473.72</td></tr><tr><td>DF</td><td>F64</td><td>C012</td><td>N6488</td><td>33200.51</td></tr><tr><td>DF</td><td>F94</td><td>C012</td><td>N6488</td><td>443.5</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N64112</td><td>82179.64</td></tr><tr><td>DF</td><td>F20</td><td>C012</td><td>N6488</td><td>78271.86</td></tr><tr><td>RF</td><td>F33</td><td>C70</td><td>N7066</td><td>7383.5</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N64731</td><td>462.14</td></tr><tr><td>DF</td><td>F523</td><td>C012</td><td>N6488</td><td>850.07</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6478</td><td>1325</td></tr><tr><td>DF</td><td>F311</td><td>C011</td><td>N62876</td><td>385538.5</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6474</td><td>2704.53</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N64131</td><td>136826.11</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6336</td><td>26199.69</td></tr><tr><td>DF</td><td>F814</td><td>C012</td><td>N6488</td><td>409.16</td></tr><tr><td>DF</td><td>F823</td><td>C012</td><td>N6488</td><td>6183.93</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6488</td><td>5486.91</td></tr><tr><td>DF</td><td>F025</td><td>C012</td><td>N6488</td><td>1794.28</td></tr><tr><td>RF</td><td>F822</td><td>C73</td><td>N7368</td><td>100022.37</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6237</td><td>2072.64</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N60623</td><td>34159.24</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6453</td><td>133188.63</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6458</td><td>9512.94</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6488</td><td>3627.93</td></tr><tr><td>RF</td><td>F022</td><td>C74</td><td>N7485</td><td>60360</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6218</td><td>1657</td></tr><tr><td>DF</td><td>F12</td><td>C012</td><td>N6488</td><td>2711.47</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6453</td><td>379520.65</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6188</td><td>-762.4</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N64131</td><td>545608.84</td></tr><tr><td>DF</td><td>F114</td><td>C012</td><td>N6488</td><td>3534.05</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6451</td><td>372505.46</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N64118</td><td>500564.28</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6455</td><td>2923.07</td></tr><tr><td>RI</td><td>F811</td><td>C13</td><td>N1321</td><td>108924</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N64116</td><td>59629.32</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N64112</td><td>34535.56</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6332</td><td>8656.99</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N64112</td><td>25565.75</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6458</td><td>36172</td></tr><tr><td>DF</td><td>F112</td><td>C012</td><td>N6488</td><td>3373.76</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6331</td><td>12373</td></tr><tr><td>DI</td><td>F812</td><td>C21</td><td>N21578</td><td>296269.15</td></tr><tr><td>DF</td><td>F213</td><td>C012</td><td>N6488</td><td>4407.76</td></tr><tr><td>RF</td><td>F520</td><td>C70</td><td>N7066</td><td>10593.84</td></tr><tr><td>DF</td><td>F70</td><td>C012</td><td>N6488</td><td>1867.44</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N64131</td><td>115717.61</td></tr><tr><td>DF</td><td>F33</td><td>C012</td><td>N6488</td><td>3682.53</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N64731</td><td>196.92</td></tr><tr><td>DF</td><td>F421</td><td>C012</td><td>N6488</td><td>31750.77</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N6488</td><td>2806589.31</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6336</td><td>8923.46</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6451</td><td>114215.5</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N64112</td><td>46806.4</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6331</td><td>10751.54</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6288</td><td>2858.57</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6332</td><td>4178.05</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6332</td><td>2660.63</td></tr><tr><td>DI</td><td>F811</td><td>C16</td><td>N16871</td><td>3720.18</td></tr><tr><td>DF</td><td>F022</td><td>C67</td><td>N678</td><td>136</td></tr><tr><td>DF</td><td>F812</td><td>C011</td><td>N611</td><td>295196.23</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6332</td><td>2972.31</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6336</td><td>7937.79</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N64118</td><td>100932.62</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N61558</td><td>12447.49</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6478</td><td>450</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N64131</td><td>58438.53</td></tr><tr><td>DF</td><td>F95</td><td>C014</td><td>N7398</td><td>15000</td></tr><tr><td>RF</td><td>F520</td><td>C70</td><td>N70841</td><td>70270.05</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6451</td><td>104537.64</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N64112</td><td>23854.77</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N6331</td><td>17493.02</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6064</td><td>4771.7</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N6478</td><td>576.28</td></tr><tr><td>DF</td><td>F82</td><td>C012</td><td>N64111</td><td>507956.13</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6488</td><td>7164.06</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N64111</td><td>1192403.83</td></tr><tr><td>DF</td><td>F813</td><td>C012</td><td>N6488</td><td>7924.74</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N64111</td><td>415003.7</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6474</td><td>162.47</td></tr><tr><td>DF</td><td>F511</td><td>C012</td><td>N6488</td><td>14528.06</td></tr><tr><td>DF</td><td>F51</td><td>C012</td><td>N6332</td><td>2602.18</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N6478</td><td>3049.86</td></tr><tr><td>DF</td><td>F022</td><td>C012</td><td>N64111</td><td>687451.71</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6451</td><td>98433</td></tr><tr><td>DF</td><td>F021</td><td>C012</td><td>N6488</td><td>1693.92</td></tr><tr><td>DF</td><td>F52</td><td>C012</td><td>N6458</td><td>7111.37</td></tr><tr><td>DF</td><td>F510</td><td>C012</td><td>N6488</td><td>613.41</td></tr><tr><td>RF</td><td>F022</td><td>C74</td><td>N7484</td><td>20011</td></tr></table>
</details>

**Comment by DavidBruant** [comment]
Il n'y a pas de ligne utilisée dans deux formules

**Comment by DavidBruant** [comment]
Par email, quelqu'un à Montreuil va travailler à corriger le xlsx pour y rajouter les lignes manquantes

**Comment by oncletom** [comment]
Il y a une partition pour le CA 2018 mais ils n'avaient pas testé ça pour 2017. Ils vont bosser dessus.

**Comment by DavidBruant** [comment]
On a reçu une correction par email, je suis sur le coup

**Comment by DavidBruant** [comment]
J'ai rajouté le complément à la suite de #69 puisque c'est le même sujet

Je vais vérifier qu'avec ce complément, on a bien une partition sur les 3 années

**Comment by DavidBruant** [comment]
a priori, ça n'est pas une partition sur les 3 années\
J'ai découverts quelques petits problèmes avec les fichiers excel existants. On va changer de process et utilisé un tableur en ligne pour être sûrs d'avoir un fichier complet et la même version de référence

**Comment by DavidBruant** [comment]
On utilise la version en ligne de Excel pour la version de référence
Je fais ça rapidement

**Comment by DavidBruant** [comment]
Avec la version actuelle de la nomenclature :

## CA 2016

les lignes suivantes ne sont pas utilisées : 

<table><tr><td>RF</td><td>F20</td><td>C74</td><td>N7476</td><td>194946</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N6488</td><td>2910911.5</td></tr><tr><td>DF</td><td>F022</td><td>C011</td><td>N6232</td><td>30</td></tr><tr><td>DI</td><td>F812</td><td>C21</td><td>N2188</td><td>58306.56</td></tr><tr><td>RF</td><td>F01</td><td>C73</td><td>N7321</td><td>58351369</td></tr><tr><td>RF</td><td>F01</td><td>C74</td><td>N746</td><td>603</td></tr><tr><td>RF</td><td>F01</td><td>C002</td><td>N002</td><td>2583139.15</td></tr><tr><td>RF</td><td>F022</td><td>C70</td><td>N70388</td><td>4557.29</td></tr><tr><td>RF</td><td>F01</td><td>C73</td><td>N7324</td><td>3755075</td></tr><tr><td>DF</td><td>F01</td><td>C014</td><td>N73921</td><td>305602.78</td></tr><tr><td>DF</td><td>F01</td><td>C014</td><td>N73925</td><td>726031</td></tr><tr><td>DF</td><td>F313</td><td>C012</td><td>N6488</td><td>32.55</td></tr><tr><td>RF</td><td>F815</td><td>C73</td><td>N7388</td><td>89323</td></tr><tr><td>RF</td><td>F01</td><td>C73</td><td>N7325</td><td>2243763</td></tr><tr><td>DF</td><td>F41</td><td>C012</td><td>N64162</td><td>12361.01</td></tr><tr><td>RF</td><td>F512</td><td>C74</td><td>N746</td><td>579148</td></tr></table>

## CA 2017

les lignes suivantes ne sont pas utilisées : 

<table><tr><td>RF</td><td>F01</td><td>C002</td><td>N002</td><td>6031472.16</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N64116</td><td>59629.32</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N6488</td><td>2806589.31</td></tr></table>

## CA 2018

les lignes suivantes ne sont pas utilisées : 

<table><tr><td>RF</td><td>F01</td><td>C002</td><td>N002</td><td>10550309.49</td></tr><tr><td>DF</td><td>F314</td><td>C012</td><td>N6488</td><td>701.84</td></tr><tr><td>RI</td><td>F12</td><td>C4541</td><td>N4541</td><td>6791.89</td></tr><tr><td>DF</td><td>F01</td><td>C014</td><td>N7391178</td><td>1689</td></tr><tr><td>RF</td><td>F91</td><td>C77</td><td>N7711</td><td>600</td></tr><tr><td>RF</td><td>F91</td><td>C74</td><td>N7478</td><td>18400</td></tr><tr><td>DF</td><td>F322</td><td>C012</td><td>N6488</td><td>377.28</td></tr><tr><td>DF</td><td>F72</td><td>C012</td><td>N6488</td><td>1479.62</td></tr><tr><td>DF</td><td>F020</td><td>C012</td><td>N6488</td><td>2701978.9</td></tr></table>

`RF F01 C002 N002` n'est pas utilisé, mais c'est bizarre, dans le XML `OpBudg` vaut `0` alors qu'il devrait ptèt valoir `1` (opération d'ordre). C'est ce que suggère la nomenclature Montreuil en tout cas

**Comment by oncletom** [comment]
Lignes manquantes avec la v12.

# CA 2018

RF | F01 | C002 | N002 | 10550309.49
-- | -- | -- | -- | --
DF | F411 | C012 | N6488 | 2233.3
RI | F12 | C4541 | N4541 | 6791.89
DF | F520 | C012 | N6488 | 1850.86
DF | F414 | C012 | N6488 | 5968.37
DF | F020 | C012 | N6488 | 2701978.9
