### ISSUE TITLE
Modéliser RD différemment de FI dans BubbleChartCluster.js

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/dataviz-finances-montreuil#66]
Mes excuses pour l'esprit d'escalier

Je fais référence à https://github.com/dtc-innovation/dataviz-finances-montreuil/pull/52/files#diff-3403f75f8095a90baae35ef0cbb6b097R36

L'état est modéliser par 4 booléens R, D, F, I, mais je pense qu'une autre modélisation serait plus proche de l'état disponible aux utilisateurs via l'interface : 

```js
{
  RD: 'R' | 'D'
  F: bool
  I : bool
}
```

En effet, d'après les maquettes, on ne regarde jamais les dépenses et les recettes en même temps, le choix est exclusif. Contrairement aux F/I où les 4 combinaisons de booléens sont possibles

**Comment by oncletom** [comment]
Aucun problème, je retombais sur une réflexion similaire pour représenter les couleurs.

Merci, bien au contraire 🙂
