### ISSUE TITLE
Explorer : ajouter un histogramme de grandes masses par année

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#73]
Entre les donuts Recettes/Dépenses et les bulles.

L'affichage est affecté par les boutons radio "Recettes" / "Dépenses"

<img width="698" alt="image" src="https://user-images.githubusercontent.com/138627/54754987-c1556c00-4bdc-11e9-9e58-55015e4442f4.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/138627/54755020-d6ca9600-4bdc-11e9-9220-ec18bb7d0ca7.png">

**Comment by DavidBruant** [comment]
Le découpage est celui des barres est le découpage du niveau 2 (au moins pour les dépenses, pas clair sur les recettes)
