### ISSUE TITLE
Page détails : remanier la contextualisation

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#74]
Pour mieux représenter la part du niveau dans l'arborescence.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/138627/54755154-3b85f080-4bdd-11e9-87c8-8ee034a14a68.png">

On peut naviguer vers un niveau plus haut :

<img width="689" alt="image" src="https://user-images.githubusercontent.com/138627/54755180-4b9dd000-4bdd-11e9-8728-b451e3080390.png">

Ou redescendre dans un autre endroit de l'arborescence :

<img width="699" alt="image" src="https://user-images.githubusercontent.com/138627/54755213-5ce6dc80-4bdd-11e9-8f59-3e465912d99e.png">

**Comment by DavidBruant** [comment]
Un truc qui a changé ici, c'est qu'on n'a plus la distinction fonctionnement/investissement parce que les éléments en fonctionnement et investissement ne sont plus les mêmes, donc plus besoin de la séparation ni de préciser sur le diagramme (mais le préciser en haut à côté du titre quand même)

C'est pas clair pour moi si c'est nécessaire de faire les deux barres (celle du haut et celle du bas)
Je peux commencer là-dessus, c'est pas beaucoup plus dur

Par contre, les sous-parties au survol, c'est cool sur ordi et inutilisable sur mobile sans souris. Je vais faire ça quand même, mais je voulais ouvrir la discussion
