### ISSUE TITLE
Cluster : afficher les infobulles au tap et neutraliser le "clic"

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#76]
Sur mobile, le "hover" n'est pas possible. Le "touch" ouvrirait l'infobulle et ne dirigerait pas vers la page Détails.

Pour aller sur la page Détails, le clic s'effectue sur le lien de l'infobulle.

Un clic en dehors de l'infobulle ferme l'infobulle.

**Comment by ariasuni** [comment]
J’ai l’impression que le plus simple est d’utiliser [`react-tappable`](https://github.com/JedWatson/react-tappable) sur les composants dont on veut qu’ils réagissent différemment entre desktop et mobile. Ça te semble correct?

**Comment by oncletom** [comment]
Peut-être qu'oui !

J'avais testé avec `onTouchStart` + `event.stopPropagation()` pour empêcher que l'événement remonte jusqu'au `onClick` mais sans succès (sous Firefox).

Du coup si `react-tappable` rend ça consistant et fonctionnel, c'est une bonne nouvelle 👍

**Comment by oncletom** [comment]
Je mets de côté, on s'oriente vers la suppression des sous-politiques et la suppression des infobulles.
